path: /Users/guill/Desktop/Universidad/2023-2024/Segundo_Semestre/VC/Practicas/Swiming_Pool_Detection
train: DATABASE/yolov8/images/train
val: DATABASE/yolov8/images/val
test: DATABASE/yolov8/images/test

#Classes
names:
  0: pool 